name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          
      - name: Set up AWS IAM
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: downloads zip to s3
        run : |
          aws s3 cp s3://gsm-ia-s3-bucket/bot_json.zip .
          unzip bot_json.zip
          ls
          
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: idol/ddilchan-bot
          stage: main
          yaml: >
            name: ddilchan-bot

            app: python@3.11

            options:
              ports: 8000
              install: pip3 install -r requirements.txt
              start: python3 main.py
              env:
                - name: Token
                  value: ${{ secrets.TOKEN }}
                - name: database_url
                  value: ${{ secrets.DATABASE_URL }}
                - name: guild_url
                  value: ${{ secrets.GUILD_URL }}
                - name: channel_url
                  value: ${{ secrets.CHANNEL_URL }}
                - name: no_meeting_vichan_gif
                  value: ${{ secrets.NO_MEETING_VICHAN_GIF }}
                - name: one_meeting_vichan_gif
                  value: ${{ secrets.ONE_MEETING_VICHAN_GIF }}
                - name: many_meeting_vichan_gif
                  value: ${{secrets.MANY_MEETING_VICHAN_GIF }}
                - name: many_many_meeting_vichan_gif
                  value: ${{ secrets.MANY_MANY_MEETING_VICHAN_GIF }}
              nodeversion: "14"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
      - name: test
        run : ls
