name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: idol/ddilchan-bot
          stage: main
          yaml: >
            name: ddilchan-bot

            app: python@3.11

            options:
              ports: 8000
              install: pip3 install -r requirements.txt
              start: echo ${{ secrets.FIREBASE_JSON }} >>
                ddillchan-firebase-adminsdk-r1wuk-712b7d43b7.json && echo ${{ secrets.MEMBER_LIST_1 }}
                >> member_list_1.json && echo ${{ secrets.MEMBER_LIST_2 }} >> member_list_2.json &&
                python3 main.py
              env:
              - name: Token
                value: ${{ secrets.TOKEN }}
              - name: database_url
                value: ${{ secrets.DATABASE_URL }}
              - name: guild_url
                value: ${{ secrets.GUILD_URL }}
              - name: channel_url
                value : ${{ secrets.CHANNEL_URL }}
              - name: no_meeting_vichan_gif
                value: ${{ secrets.NO_MEETING_VICHAN_GIF }}
              - name: one_meeting_vichan_gif
                value: ${{ secrets.ONE_MEETING_VICHAN_GIF }}
              - name: many_meeting_vichan_gif
                value: ${{ secrets.MANY_MEETING_VICHAN_GIF }}
              - name: many_many_meeting_vichan_gif
                value: ${{ secrets.MANY_MANY_MEETING_VICHAN_GIF }}
              buildenv:
                - name: firebase_json
                  value: ${{ secrets.FIREBASE_JSON }}
                - name: member_list_1
                  value: ${{ secrets.MEMBER_LIST_1 }}
                - name: member_list_2
                  value: ${{ secrets.MEMBER_LIST_2 }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
